spring.application.name=PointsAPI2.0
spring.config.import=optional:file:.env[.properties]

logging.level.com.vdska.pointsapi2.aspect.logging.controller=info
logging.level.com.vdska.pointsapi2.aspect.logging.exception=info
logging.level.com.vdska.pointsapi2.aspect.logging.service=info
logging.level.com.vdska.pointsapi2.aspect.logging.service.JWTServiceAspect=debug

spring.datasource.url=jdbc:h2:mem:default
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

spring.rabbitmq.host=${RABBIT_MQ_HOST:localhost}
spring.rabbitmq.port=${RABBIT_MQ_PORT:5672}
spring.rabbitmq.username=${RABBIT_MQ_USERNAME:guest}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD:guest}
mail.queue.name=${RABBIT_MQ_QUEUE_NAME:DefaulQueue}

spring.data.redis.database=${REDIS_DATABASE_NAME:0}
spring.data.redis.host=${REDIS_DATABASE_HOST:localhost}
spring.data.redis.port=${REDIS_DATABASE_PORT:6379}

confirmationlink.ttl=86400
confirmationlink.prefix=${CONFIRMATION_LINK_PREFIX}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXP}
jwt.refresh.expiration=${JWT_REFRESH_EXP}

auth.registration.role=ROLE_UNVERIFIED_USER
auth.verification.role=ROLE_USER