spring.application.name=PointsAPI2.0
spring.config.import=optional:file:.env[.properties]

logging.level.com.vdska.pointsapi2.aspect.logging.controller=debug
logging.level.com.vdska.pointsapi2.aspect.logging.exception=debug
logging.level.com.vdska.pointsapi2.aspect.logging.service=debug

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.sql.init.mode=always

spring.rabbitmq.host=${RABBIT_MQ_HOST:localhost}
spring.rabbitmq.port=${RABBIT_MQ_PORT:5672}
spring.rabbitmq.username=${RABBIT_MQ_USERNAME:guest}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD:guest}
mail.confirm.queue.name=${RABBIT_MQ_QUEUE_CONFIRMATION_NAME:DefaultQueue}
mail.otp.queue.name=${RABBIT_MQ_QUEUE_OTP_NAME:DefaultQueue}

spring.data.redis.database=${REDIS_DATABASE_NAME:0}
spring.data.redis.host=${REDIS_DATABASE_HOST:localhost}
spring.data.redis.port=${REDIS_DATABASE_PORT:6379}

confirmationlink.ttl=86400
confirmationlink.prefix=${CONFIRMATION_LINK_PREFIX:http://localhost:5173/confirm?id=}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXP}
jwt.refresh.expiration=${JWT_REFRESH_EXP}

otp.ttl=120
chid.ttl=120

checkout.minio.mode=true
checkout.minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
checkout.minio.access-key=${MINIO_ACCESS_KEY}
checkout.minio.secret-key=${MINIO_SECRET_KEY}
checkout.minio.bucket-name=${MINIO_BUCKET_NAME}
checkout.minio.object-name=${MINIO_OBJECT_NAME}